### PR TITLE
Remove hostname from app.listen

### PR DESCRIPTION
**Pull request by manan19**
Running into issues with port binding if we specify the hostname for an express server 

https://stackoverflow.com/questions/48349056/cant-connect-to-node-server-on-amazon-ec2/48349104

### CODE REVIEW

**Comment by gabeio** [comment]
I think I get what you are trying to do here, but I think a better change might be to default the hostname to `0.0.0.0`, which will leave open the capability of closing off the application to the internet.

**Review by gabeio — APPROVED** [review]
Seems reasonable as a default.

**Comment by Bind** [comment]
Heyo looks straightforward! @manan19 if could you squash your commits I'll happily merge

**Comment by manan19** [comment]
@Bind There should be a squash and merge option, right?

image

**Comment by Bind** [comment]
You're right, merged!

**Pull request merged**
